ClickApp/ViewModels/UserSkillViewModel.cs
using ClickApp.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ClickApp.ViewModels
{
    public class UserSkillViewModel
    {
        public int Id { get; set; }

        
        [Display(Name = "Year when skill developed")]
        public DateTime? YearSkillStarted { get; set; }

        [Display(Name = "Experience")]
        public string? ExperienceDescription { get; set; }
        [Required]
        [Display(Name = "Experience level")]
        public int ExperienceLevel { get; set; }

        [Display(Name = "Latest certificate")]
        public string? LatestCertificateImageUrl { get; set; }

        //public string UserId { get; set; }
        //public ApplicationUser User { get; set; }
        public int SkillId { get; set; }
    }
}

ClickApp/Controllers/UserSkillsController.cs
using ClickApp.Mappings;
using ClickApp.Models;
using ClickApp.Services.Interfaces;
using ClickApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClickApp.Controllers
{
    public class UserSkillsController : Controller
    {
        private readonly IUserSkillsService _userSkillsService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ISkillsService _skillsService;
        public UserSkillsController(IUserSkillsService userSkillsService, UserManager<ApplicationUser> userManager, ISkillsService skillsService)
        {
            _userSkillsService = userSkillsService;
            _userManager = userManager;
            _skillsService = skillsService;
        }
        
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> EditUserSkills(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);

            if (user == null)
            {
                return RedirectToAction("Error", "Home");
            }
            var userDetails = user.ToEditUserViewModel();

            user.Skills = _userSkillsService.GetAllSkillsForUser(user.Id);
            if (user.Skills != null)
            {
                var listOfUserSkills = new List<SkillViewModel>();
                foreach (var userSkill in user.Skills)
                {
                    var skill = _skillsService.GetById(userSkill.SkillId).ToSkillViewModel();
                    listOfUserSkills.Add(skill);
                }

                userDetails.Skills = listOfUserSkills;
            }
            else
            {
                userDetails.Skills = new List<SkillViewModel>();
            }

            var skills = _skillsService.GetAll();
            var skillsForView = skills.Select(x => x.ToSkillViewModel()).ToList();
            userDetails.AllSkills = skillsForView;

            return View(userDetails);
            //return RedirectToAction("Details", "User", new { userId = userId });
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel user)
        {
            if (ModelState.IsValid)
            {
                var userFromDb = await _userManager.FindByIdAsync(user.Id);
                if (userFromDb == null)
                {
                    return RedirectToAction("Error", "Home");
                }
                var updatedUser = user.ToModel();


                if (user.Skills != null)
                {
                    //var skillsToUpdate = user.Skills.Select(x => x.ToUserSkillModel()).ToList();
                    //updatedUser.Skills = skillsToUpdate;

                    var listOfUserSkills = new List<UserSkill>();
                    foreach (var userSkill in user.Skills)
                    {
                        var skill = _userSkillsService.GetById(userSkill.Id);
                        listOfUserSkills.Add(skill);
                    }

                    updatedUser.Skills = listOfUserSkills;
                }
                else
                {
                    updatedUser.Skills = new List<UserSkill>();
                }

                if (user.Interests != null)
                {
                    var listOfUserInterests = new List<UserInterest>();
                    foreach (var userInterest in user.Interests)
                    {
                        //var interest = _userInterestsService.GetById(userInterest.Id);
                        //listOfUserInterests.Add(interest);
                    }

                    updatedUser.Interests = listOfUserInterests;
                }
                else
                {
                    updatedUser.Interests = new List<UserInterest>();
                }

                userFromDb.Name = updatedUser.Name;
                userFromDb.LastName = updatedUser.LastName;
                userFromDb.Address = updatedUser.Address;
                userFromDb.City = updatedUser.City;
                userFromDb.Country = updatedUser.Country;
                userFromDb.ProfilePhotoURL = updatedUser.ProfilePhotoURL;
                userFromDb.Description = updatedUser.Description;
                userFromDb.Skills = updatedUser.Skills;
                userFromDb.Interests = updatedUser.Interests;


                await _userManager.UpdateAsync(userFromDb);

                return RedirectToAction("Details");
            }
            else
            {
                return View(user);
            }
        }
    }
}

ClickApp/Views/UserSkills/EditUserSkills.cshtml
@model ClickApp.ViewModels.EditUserViewModel

@{
    ViewData["Title"] = "Edit User Skills";
}
@section Styles{
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
}
<div class="row justify-content-between">
    <div>
        <ul id="listOfSkills">
            <h3>Skills list</h3>
            @foreach (var skill in Model.Skills)
            {
                <li value="@skill.Id" class="row align-items-center">
                    <div class="col p-1 rounded bg-success text-light" style="width:250px">@skill.Name</div>
                    <a class="col" asp-controller="UserSkills" asp-action="Delete" asp-route-id="@skill.Id">
                        <i class="far fa-times-circle"></i>
                    </a>
                </li>
                @Html.ActionLink("Delete", "Delete", new { id = Model.Id })
            }
        </ul>
    </div>

    <div class="form-group align-items-center">
        <div class="row m-1 p-1 align-items-center">
            <div class="col" style="width:200px">
                <label class="control-label text-primary" for="skillId">Add skill here =></label>
            </div>
            <div class="col">
                <select name="skillId" Id="skillId" class="form-control" required>
                    @foreach (var skill in Model.AllSkills)
                    {
                        if (!Model.Skills.Exists(x => x.Name == skill.Name))
                        {
                            <option value="@skill.Id">@skill.Name</option>
                        }

                    }
                </select>
            </div>
            <div class="col">
                <button class="btn btn-primary m-1 text-light inline-block" onclick="addSkill(@Model.Id)">Add skill</button>
            </div>
        </div>
    </div>

</div>

@section Scripts {

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        function addSkill(userId) {
            alert("Hi");
            var skills = _userSkillsService.GetAllSkillsForUser(userId);

            var skillId = document.getElementById("skillId");
            var skillIdValue = skillId.value;

            var skillFromDb = _skillsService.GetById(skillIdValue);
            var skillFromDbInViewModel = skillFromDb.ToSkillViewModel();

            var element = null;
            for (var i = 0; i < userSkills.length; i++) {
                if (userSkills[i] == skillFromDbInViewModel) {
                    element = userSkills[i];
                } else {
                    continue;
                }
            }
            if (element == null) {
                var list = document.getElementById("listOfSkills");
                var listItem = document.createElement("li");
                listItem.innerText = skillFromDbInViewModel;
                list.appendChild(listItem);
            }
            skillId.value = null;
        }
    </script>
}