ClickApp/Controllers/OfferController.cs
using ClickApp.Mappings;
using ClickApp.Models;
using ClickApp.Services.Interfaces;
using ClickApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace ClickApp.Controllers
{
    public class OfferController : Controller
    {
        private readonly IOffersService _offersService;
        private readonly UserManager<ApplicationUser> _userManager;
        public OfferController(IOffersService offersService, UserManager<ApplicationUser> userManager)
        {
            _offersService = offersService;
            _userManager = userManager;
        }
        
        public IActionResult Overview()
        {
            return View();
        }
        public IActionResult GetAllWithFilter(string offerTitle, bool isProffesional, string errorMessage, string successMessage)
        {
            try
            {
                if (errorMessage != null)
                {
                    ViewBag.ErrorMessage = errorMessage;
                }

                if (successMessage != null)
                {
                    ViewBag.SuccessMessage = successMessage;
                }
                var offers = _offersService.GetAllPublicWithFilter(offerTitle, isProffesional);

                var viewOffers = offers.Select(x => x.ToOfferViewModel()).ToList();

                return View(viewOffers);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }
        }
        
        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            var offer = new CreateOfferViewModel();
            offer.ValidUntil = DateTime.Now.AddYears(5).Date;
            return View(offer);
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(CreateOfferViewModel createOfferViewModel,string returnUrl)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var user = User;
                    var userFromDb = await _userManager.FindByNameAsync(user.Identity.Name);

                    var offer = createOfferViewModel.ToModel();
                    offer.DateCreated = DateTime.Now;
                    offer.UserId = userFromDb.Id;
                    offer.User = userFromDb;
                    _offersService.Create(offer);
                    if (returnUrl != null)
                    {
                        return Redirect(returnUrl);
                    }
                    return RedirectToAction("GetAllWithFilter", new { isProffesional = offer.IsProfessional });
                }
                else
                {
                    return View(createOfferViewModel);
                }
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }
        }
        
        [HttpGet]
        [Authorize]
        public IActionResult Edit(int id)
        {
            try
            {
                var offer = _offersService.GetById(id);
                if (offer == null)
                {
                    return RedirectToAction("GetAllWithFilter", new { isProffesional = offer.IsProfessional, ErrorMessage = $"There are no active offers with ID {id}." });
                }
                var offerForView = offer.ToOfferViewModel();

                return View(offerForView);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }
        }
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(OfferViewModel offerViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var offer = offerViewModel.ToModel();
                    var response = _offersService.Update(offer);

                    if (response.IsSuccessful)
                    {
                        return RedirectToAction("Details", new { id = offer.Id, successMessage = $"The carpool offer with ID {offer.Id} has been successfully updated." });
                    }
                    else
                    {
                        return RedirectToAction("Details", new { id = offer.Id, ErrorMessage = response.Message });
                    }
                }
                else
                {
                    return View(offerViewModel);
                }
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }
        }
        
        [Authorize]
        public IActionResult Delete(int id)
        {
            try
            {
                var response = _offersService.Delete(id);

                if (response.IsSuccessful)
                {
                    return RedirectToAction("Overview", new { successMessage = response.Message });
                }
                return RedirectToAction("Overview", new { errorMessage = response.Message });
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }
        }
        public async Task<IActionResult> Details(int id, string successMessage, string errorMessage)
        {
            try
            {
                if (successMessage != null)
                {
                    ViewBag.SuccessMessage = successMessage;
                }
                if (errorMessage != null)
                {
                    ViewBag.ErrorMessage = errorMessage;
                }

                var offer = _offersService.GetById(id);
                if (offer == null)
                {
                    return RedirectToAction("Overview", new { ErrorMessage = $"There are no offers with ID {id}." });
                }

                var offerForView = offer.ToOfferViewModel();
                return View(offerForView);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }
        }
    }
}

ClickApp/Controllers/UserController.cs
using ClickApp.Mappings;
using ClickApp.Models;
using ClickApp.Services.Interfaces;
using ClickApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClickApp.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUserSkillsService _userSkillsService;
        private readonly ISkillsService _skillsService;
        private readonly IInterestsService _interestsService;
        private readonly IUserInterestsService _userInterestsService;
        private readonly IFriendshipService _friendshipService;
        private readonly IFriendshipRequestsService _friendshipRequestsService;
        private readonly IOffersService _offersService;
        private readonly ICarpoolOfferService _carpoolOfferService;
        public UserController(UserManager<ApplicationUser> userManager, IUserSkillsService userSkillsService, ISkillsService skillsService, IInterestsService interestsService, IUserInterestsService userInterestsService, IFriendshipService friendshipService, IFriendshipRequestsService friendshipRequestsService, IOffersService offersService, ICarpoolOfferService carpoolOfferService)
        {
            _userManager = userManager;
            _userSkillsService = userSkillsService;
            _skillsService = skillsService;
            _interestsService = interestsService;
            _userInterestsService = userInterestsService;
            _friendshipService = friendshipService;
            _friendshipRequestsService = friendshipRequestsService;
            _offersService = offersService;
            _carpoolOfferService = carpoolOfferService;
        }
        
        [Authorize]
        public async Task<IActionResult> Details(string userId, string successMessage, string errorMessage)
        {
            try
            {
                if (successMessage != null)
                {
                    ViewBag.SuccessMessage = successMessage;
                }
                if (errorMessage != null)
                {
                    ViewBag.ErrorMessage = errorMessage;
                }

                var user = await _userManager.GetUserAsync(User);

                if (userId != null && userId != "")
                {
                    user = await _userManager.FindByIdAsync(userId);
                }

                if (user == null)
                {
                    return RedirectToAction("Error", "Home");
                }
                user.Skills = _userSkillsService.GetAllSkillsForUser(user.Id);
                user.Interests = _userInterestsService.GetAllSkillsForUser(user.Id);
                user.Offers = _offersService.GetAllOffersForUser(user.Id);

                var userDetails = user.ToUserViewModel();

                var userCarpoolOffers = _carpoolOfferService.GetAllCarpoolOffersByUserId(user.Id);
                var userCarpoolOffersListView = new List<CarpoolOfferViewModel>();
                if (userCarpoolOffers != null)
                {
                    userCarpoolOffersListView = userCarpoolOffers.Select(x => x.ToCarpoolOfferViewModel()).ToList();
                }
                userDetails.CarpoolOffers = userCarpoolOffersListView;

                if (user.Skills != null)
                {
                    var userSkillIds = user.Skills.Select(x => x.SkillId).ToList();
                    var skills = new List<Skill>();
                    foreach (var id in userSkillIds)
                    {
                        var skill = _skillsService.GetById(id);
                        skills.Add(skill);
                    }

                    var userSkillsForView = skills.Select(x => x.ToSkillViewModel()).ToList();
                    userDetails.Skills = userSkillsForView;

                }
                else
                {
                    userDetails.Skills = new List<SkillViewModel>();
                }

                if (user.Interests != null)
                {
                    var userInterestIds = user.Interests.Select(x => x.InterestId).ToList();
                    var interests = new List<Interest>();
                    foreach (var id in userInterestIds)
                    {
                        var interest = _interestsService.GetById(id);
                        interests.Add(interest);
                    }

                    var userInterestsForView = interests.Select(x => x.ToInterestViewModel()).ToList();
                    userDetails.Interests = userInterestsForView;
                }
                else
                {
                    userDetails.Interests = new List<InterestViewModel>();
                }

                var friendsListView = new List<UserCardViewModel>();
                var friends = _friendshipService.GetAllUserFriendships(user);
                if (friends != null)
                {
                    foreach (var friendship in friends)
                    {
                        var friend = await _userManager.FindByIdAsync(friendship.FriendsId);
                        var friendCardModel = friend.ToUserCardViewModel();
                        friendsListView.Add(friendCardModel);
                    }
                }
                userDetails.Friends = friendsListView;

                var friendRequestsListView = new List<UserCardViewModel>();
                var friendRequests = _friendshipRequestsService.GetAllUserFriendRequests(user);
                if (friendRequests != null)
                {
                    foreach (var friendRequest in friendRequests)
                    {
                        var friend = await _userManager.FindByIdAsync(friendRequest.UserId); ;
                        var friendCardModel = friend.ToUserCardViewModel();
                        friendRequestsListView.Add(friendCardModel);
                    }
                }
                userDetails.RequestingUsers = friendRequestsListView;

                return View(userDetails);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            try
            {
                var user = await _userManager.FindByIdAsync(id);
                user.Skills = _userSkillsService.GetAllSkillsForUser(user.Id);
                user.Interests = _userInterestsService.GetAllSkillsForUser(user.Id);
                if (user == null)
                {
                    return RedirectToAction("Error", "Home");
                }

                var userDetails = user.ToEditUserViewModel();
                if (user.Skills != null)
                {
                    var listOfUserSkills = new List<SkillViewModel>();
                    foreach (var userSkill in user.Skills)
                    {
                        var skill = _skillsService.GetById(userSkill.SkillId).ToSkillViewModel();
                        listOfUserSkills.Add(skill);
                    }

                    userDetails.Skills = listOfUserSkills;
                }
                else
                {
                    userDetails.Skills = new List<SkillViewModel>();
                }

                if (user.Interests != null)
                {
                    var listOfUserInterests = new List<InterestViewModel>();
                    foreach (var userIngterest in user.Interests)
                    {
                        var interest = _interestsService.GetById(userIngterest.InterestId).ToInterestViewModel();
                        listOfUserInterests.Add(interest);
                    }

                    userDetails.Interests = listOfUserInterests;
                }
                else
                {
                    userDetails.Interests = new List<InterestViewModel>();
                }

                //var interests = _interestsService.GetAll();
                //var interestsForView = interests.Select(x => x.ToInterestViewModel()).ToList();
                //userDetails.AllInterests = interestsForView;

                return View(userDetails);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home");
            }
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var userFromDb = await _userManager.FindByIdAsync(user.Id);
                    if (userFromDb == null)
                    {
                        return RedirectToAction("Error", "Home");
                    }
                    var updatedUser = user.ToModel();


                    if (user.Skills != null)
                    {
                        //var skillsToUpdate = user.Skills.Select(x => x.ToModel()).ToList();
                        //updatedUser.Skills = skillsToUpdate;

                        var listOfUserSkills = new List<UserSkill>();
                        foreach (var userSkill in user.Skills)
                        {
                            var skill = _userSkillsService.GetById(userSkill.Id);
                            listOfUserSkills.Add(skill);
                        }

                        updatedUser.Skills = listOfUserSkills;
                    }
                    else
                    {
                        updatedUser.Skills = new List<UserSkill>();
                    }

                    if (user.Interests != null)
                    {
                        var listOfUserInterests = new List<UserInterest>();

ClickApp/Views/Shared/_Layout.cshtml
@using ClickApp.Models;
@using Microsoft.AspNetCore.Identity;

@inject UserManager<ApplicationUser> _userManager;
@using ClickApp.Services.Interfaces;
@inject IMessagesService _messagesService;


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClickApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/spinner.css" />
    @RenderSection("Styles", required: false)

</head>
<body>
    <header>
        <nav class=" navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                
                @if (User.Identity.IsAuthenticated)
                {
                    <a class="navbar-brand" asp-area="" asp-controller="User" asp-action="Details">My profile</a>
                }
                else
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ClickApp</a>
                }
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Offer" asp-action="Overview">Get Help</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CarpoolOffer" asp-action="Overview">Carpool</a>
                        </li>

                        @if (User.Identity.IsAuthenticated)
                        {
                            var user = await _userManager.FindByNameAsync(User.Identity.Name);
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="JournalEntry" asp-action="Overview" asp-route-userId="@user.Id">Journal</a>
                            </li>
                            <li class="nav-item">
                                @{var allMessages = _messagesService.GetAllReceivedUserMessages(user.Id);
                                    var ifNotSeenMessage = _messagesService.CheckIfNotSeenMessage(allMessages);
                                }
                                @if (ifNotSeenMessage)
                                {
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Message" asp-action="Overview" asp-route-userId="@user.Id">Messages<span class="text-danger">*</span></a>
                                }
                                else
                                {
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Message" asp-action="Overview" asp-route-userId="@user.Id">Messages</a>
                                }
                            </li>
                        }
                        @*@if (User.IsInRole("ContentCreator") || User.IsInRole("Admin"))
                            {*@
                        @*<li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Manage
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Skill" asp-action="Overview">Manage Skills</a>
                                    </li>

                                    <li>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Interest" asp-action="Overview">Manage Interests</a>
                                    </li>
                                    <li>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="GeneralField" asp-action="Overview">Manage General fields</a>
                                    </li>

                                </ul>
                            </li>*@
                        @*}*@

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - ClickApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>*@

    <div class="container p-3">
        <div class="row " id="card-container">
            <div class="loader" style="display: none" id="loader">Loading...</div>
            @*<div class="lds-dual-ring"></div>*@
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>